#!/usr/bin/env bash

set -eu

readonly branch="$1"

if [[ "help" == "${branch}" ]]; then
  echo "usage:"
  echo "===="
  echo ""
  echo "start-mob-session <branch name>"
  exit 1
fi

git fetch --prune

readonly key="$(git branch --all | grep remote | grep -v HEAD | peco)"
readonly remote="$(git branch --all | grep remote | grep -v HEAD | grep "${key}" | sed -e 's/ //g' -e 's/remotes\///g')"
readonly base="$(echo "${remote}" | cut -d'/' -f2-)"

git checkout -b "${branch}" "${remote}"

git commit --allow-empty -m "initial commit for ${branch}"
gh pr create --base "${base}" --title "[WIP] ${branch}" --body "" --draft --assignee @me