#!/usr/bin/env bash

set -eu

readonly branch="$1"

if [[ "help" == "${branch}" ]]; then
  echo "usage:"
  echo "===="
  echo ""
  echo "start-mob-session <branch name>"
  exit 1
fi

declare base
if [[ "" == "${BASE_BRANCH}" ]]; then
  base="develop"
else
  base="${BASE_BRANCH}"
fi

git fetch --prune
git checkout -b "${branch}" origin/"${base}"

git commit --allow-empty -m "initial commit for ${branch}"
gh pr create --base "${base}" --title "[WIP] ${branch}" --body "" --draft

