#!/usr/bin/env bash

set -eu

readonly branch="$1"

if [[ "help" == "${branch}" ]]; then
  echo "usage:"
  echo "===="
  echo ""
  echo "start-mob-session <branch name>"
  exit 1
fi

git fetch --prune

readonly base="$(git branch --all | grep origin | grep -v HEAD | cut -d'/' -f3- | peco)"

git checkout -b "${branch}" origin/"${base}"

git commit --allow-empty -m "initial commit for ${branch}"
gh pr create --base "${base}" --title "[WIP] ${branch}" --body "" --draft

